finish login Sign Up Button
Art1us/trading_bot_front pull request #107
Opened 2023-01-01 17:39 UTC by Alex-creatorA

2023-01-01 19:16 UTC, Art1us requested changes
Нормас, только поменя закомментированное

2023-01-01 19:16 UTC, Art1us commented on src/components/Header/Header.js
> +          <div className="burgerMenu__user">
BurgerMenu?

2023-01-01 19:16 UTC, Art1us commented on src/components/Header/Header.js
> +                <p className="heder__userName">Hello username</p>
heder?

2023-01-02 18:53 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +                <p className="heder__userName">Hello username</p>
done

2023-01-02 18:53 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +          <div className="burgerMenu__user">
done

2023-01-02 19:23 UTC, Art1us approved these changes
Красава

2023-01-02 19:23 UTC, merged