Features/209.new wecome page
Art1us/trading_bot_front pull request #111
Opened 2023-01-02 18:16 UTC by Alex-creatorA

2023-01-02 19:51 UTC, Art1us requested changes
Норм, только исправь закомментированное

2023-01-02 19:51 UTC, Art1us commented on src/pages/Welcome/Welcome.css
> +  font-family: Ppagrandir, sans-serif;
убери. Пусть все будет дефолтным шрифтом

2023-01-02 19:51 UTC, Art1us commented on src/pages/Welcome/Welcome.css
> +  grid-column-gap: 12px;
у тебя флекс контейнер, гридов тут быть не должно
Пробуй ul display flex

2023-01-02 19:51 UTC, Art1us commented on src/pages/Welcome/Welcome.js
> +      <footer className="welcome__footer">
Тут надо вынести футер в отдельный компонент. Создать там локальный массив с айди, названием и ссылкой (как в бургер меню), проитерировать через map, создавая лишки и воровнять все флексом

2023-01-02 21:12 UTC, Alex-creatorA commented on src/pages/Welcome/Welcome.css
> +  font-family: Ppagrandir, sans-serif;
done

2023-01-03 16:19 UTC, Alex-creatorA commented on src/pages/Welcome/Welcome.css
> +  grid-column-gap: 12px;
done

2023-01-03 16:19 UTC, Alex-creatorA commented on src/pages/Welcome/Welcome.js
> +      <footer className="welcome__footer">
done

2023-01-03 17:22 UTC, Art1us requested changes

2023-01-03 17:22 UTC, Art1us commented on src/pages/Footer/Footer.js
> +          <Link to={item.link} key={item.id} style={{ textDecoration: "none" }}>
item.link не определен

2023-01-03 17:28 UTC, Art1us approved these changes
Красава

2023-01-03 17:29 UTC, merged