create profile pages
Art1us/trading_bot_front pull request #146
Opened 2023-01-12 20:43 UTC by VadimGalian

2023-01-12 21:07 UTC, Art1us requested changes
Норм, только добавь функционал кнопке создания нового бота (редирект на /main)

Также ты можешь вынести в отдельный компонент весь хедер элемента, а не только кнопку. Застайлить одинаково и передать через пропсы тайтл каждого отдельного компонента.

Сгладь края Change кнопке
И добавь курсоры всем кнопкам
А также комментарии

2023-01-12 21:07 UTC, Art1us commented on src/components/ProfileItems/Dashboard/Dashboard.js
> +              Your balance: 2.228.228 <SiBitcoinsv />
Иконка - это див грубо говоря. Лучше чтоб текст не был сиблингом дива. Т.е. лучше вынести за p таг, так как это накладывает ограничения при стилизации

2023-01-12 21:07 UTC, Art1us commented on src/components/ProfileItems/NewBotBtn/NewBotBtn.js
> +      <button className="newBotBtn__creatBot">Create new bot</button>
Добавь функционал - линк на /main

2023-01-13 19:46 UTC, VadimGalian commented on src/components/ProfileItems/Bots/Bots.js
> +        Bots <NewBotBtn />
done

2023-01-13 19:47 UTC, VadimGalian commented on src/components/ProfileItems/Bots/Bots.js
> +        <table cellspacing="0">
ne done

2023-01-13 19:48 UTC, VadimGalian commented on src/components/ProfileItems/Dashboard/Dashboard.js
> +              Your balance: 2.228.228 <SiBitcoinsv />
done

2023-01-13 19:48 UTC, VadimGalian commented on src/components/ProfileItems/NewBotBtn/NewBotBtn.js
> +      <button className="newBotBtn__creatBot">Create new bot</button>
done

2023-01-13 19:57 UTC, VadimGalian commented on src/components/ProfileItems/Bots/Bots.js
> +        <table cellspacing="0">
done

2023-01-13 20:18 UTC, Art1us approved these changes

2023-01-13 20:23 UTC, Art1us approved these changes

2023-01-13 20:24 UTC, merged