Features/10.exchange edit modal
Art1us/trading_bot_front pull request #16
Opened 2022-12-18 22:20 UTC by VadimGalian

1st css style, finished html

2022-12-18 22:35 UTC, Art1us requested changes
Все круто, красава.
Мелочи:
1. Секретный ключ не должно быть видно, это как пароль
2. курсор поинтер
3. зеленая кнопка стремно выглядит, сделай ее прозрачной с синей рамкой в 1-2 пикселя (как на странице логина)

2022-12-19 11:26 UTC, Art1us requested changes
Збсь.
Только убери автозаполнение и все круто

2022-12-19 12:07 UTC, VadimGalian commented
> 

исправь кнопку редактирования биржи

2022-12-19 12:21 UTC, Art1us approved these changes

2022-12-19 12:21 UTC, merged