finish burger Menu
Art1us/trading_bot_front pull request #41
Opened 2022-12-25 16:37 UTC by Alex-creatorA

2022-12-25 17:23 UTC, Art1us requested changes
1.Высота меню по последнему элементу, а не сверху до низу
2.Стили как в тесле

А так, красава!

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +ul li a {
Никогда не делай стили html элементам. Они будут работаеть на всей странице

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +            <li>
1. Добавь Link компонент 
2. Не забудь дать уникальный key атрибут итерируемым элементам
3. Убери а таг, замени на p
4. Убери дефолтные стили ссылок

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +    <div className={active ? "menu active" : "menu"}>
Учи шаблонные литералы https://www.youtube.com/watch?v=ds0SKe0nzZs&ab_channel=LuckySpike

1. Сделать чтоб menu класс оставался, а active - переключался
2. Компонент у тебя burgerMenu, так что класс называй burgerMenu
3. И active класс переименуй на что-то более специфичное (burgerActive)
4. Обновить пропсы на новые имена

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/Header.js
> +    { value: "Main", href: "/main" },
1. Добавь id, чтоб позже использовать их в качестве key при итерации 
2. Поменяй href на link
3. Путь сделай #

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/Header.js
> +              onClick={() => setBurgerMenuActive(!BurgerMenuActive)}
setCount(prevCount => !prevCount)}

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/Header.js
> +        setActive={setBurgerMenuActive}
Лучше передавать пропсы под одинаковыми именами
setBurgerMenuActive={setBurgerMenuActive}

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/Header.js
> +              className="header__elments-item--right burgerBtn"
burgerBtn class ?

2022-12-25 17:23 UTC, Art1us commented on src/components/Header/Header.js
> +  const [BurgerMenuActive, setBurgerMenuActive] = useState(false);
Camel case
В JS/React'e все имена функций и переменных (кроме классов и компонентов) начинаются с маленькой буквы

2022-12-26 14:03 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +ul li a {
done

2022-12-26 14:03 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +            <li>
done

2022-12-26 14:04 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +    { value: "Main", href: "/main" },
done

2022-12-26 14:04 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +              onClick={() => setBurgerMenuActive(!BurgerMenuActive)}
done

2022-12-26 14:05 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +        setActive={setBurgerMenuActive}
done

2022-12-26 14:05 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +              className="header__elments-item--right burgerBtn"
done

2022-12-26 14:06 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +  const [BurgerMenuActive, setBurgerMenuActive] = useState(false);
done

2022-12-26 18:02 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +  const items  = [
done

2022-12-26 18:02 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +              onClick={() => setBurgerMenuActive((prevCount) => !prevCount)}
done

2022-12-26 18:02 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +            <li className="BurgerMenu__item" key={items.id} >
done

2022-12-26 18:03 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +
done

2022-12-26 18:03 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +.BurgerMenu {
done

2022-12-26 18:18 UTC, Art1us requested changes
оставил комменты...

2022-12-26 18:18 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +.burgerMenu__list .BurgerMenu__item burgerMenu__link {
Ошибка в последнем классе

2022-12-26 18:18 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +  burgerMenuitems,
camelCase
Items

2022-12-26 18:18 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +    <div className={burgerMenuActive ? `burgerMenu active` : `burgerMenu`}>
опять неправильно. ты просто поменял кавычки и ничего не изменилось

2022-12-26 18:18 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +            <Link to={item.link} key={item.id} className="burgerMenu__link">
Зачем тут класс, в приложении везде просто инлайн стайл

2022-12-26 18:18 UTC, Art1us commented on src/components/Header/Header.js
> +              onClick={() => setBurgerMenuActive((prevCount) => !prevCount)}
Не поменял

2022-12-26 18:25 UTC, Art1us commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +    <div className={burgerMenuActive ? `burgerMenu active` : `burgerMenu`}>
`className={`burgerMenu ${burgerMenuActive ? "active" : ""}`}`

2022-12-26 19:30 UTC, Alex-creatorA commented on src/components/Header/Header.js
> +              onClick={() => setBurgerMenuActive((prevCount) => !prevCount)}
поменял

2022-12-26 19:30 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.css
> +.burgerMenu__list .BurgerMenu__item burgerMenu__link {
сделал не проебал сам

2022-12-26 19:31 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +  burgerMenuitems,
сделал

2022-12-26 19:31 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +    <div className={burgerMenuActive ? `burgerMenu active` : `burgerMenu`}>
нет я все сделал

2022-12-26 19:36 UTC, Alex-creatorA commented on src/components/Header/BurgerMenu/BurgerMenu.js
> +            <Link to={item.link} key={item.id} className="burgerMenu__link">
обединил классы

2022-12-26 19:43 UTC, Art1us requested changes
Все круто, только добавь снизу пару пикселей (10)

2022-12-26 19:56 UTC, Art1us submitted a review, later dismissed
Красава

2022-12-26 20:01 UTC, Art1us approved these changes

2022-12-26 20:04 UTC, merged