finish login page
Art1us/trading_bot_front pull request #8
Opened 2022-12-17 12:54 UTC by Alex-creatorA

2022-12-17 12:58 UTC, Art1us requested changes
BEM convention

2022-12-17 12:58 UTC, Art1us commented on src/pages/Login/Login.css
> +.form {
BEM!!!

2022-12-18 18:17 UTC, Art1us reviewed
1. BEM!!

2022-12-18 19:48 UTC, VadimGalian commented on src/pages/Login/Login.css
> +.btn__login__yellow:hover {
Поменял классы кнопок

2022-12-18 19:49 UTC, VadimGalian commented on src/pages/Login/Login.js
> +        <div className="btn__login btn__login__violet">Sign in</div>
> Опять BEM!!!
> 
> У тебя блок: login
> 
> Значит у кнопки должен быть класс: login__sign-in-btn или как-то так

Братуха, я всё исправил

2022-12-18 19:50 UTC, Art1us approved these changes

2022-12-18 19:55 UTC, Art1us approved these changes
Теперь все круто!

2022-12-18 19:56 UTC, merged